export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_USER = 'AUTH_USER';
export const API_ERROR= 'API_ERROR';
export const RECEIVE_USERS_ = 'RECEIVE_USERS_';
export const RECEIVE_EMPLOYEES_ = 'RECEIVE_EMPLOYEES_';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
