export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_USER = 'AUTH_USER';
export const RECEIVE_ALL_USERS_SUCCESS = 'RECEIVE_ALL_USERS_SUCCESS';
export const RECEIVE_ALL_USERS_FAILURE = 'RECEIVE_ALL_USERS_FAILURE';
