export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_USER = 'AUTH_USER';
export const API_ERROR= 'API_ERROR';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const RECEIVE_EMPLOYEES = 'RECEIVE_EMPLOYEES';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const RECEIVE_FILTERED_RESULTS = 'RECEIVE_FILTERED_RESULTS';
